"""Stage 5 — calibration points CSV and HydroBayesCal config emit.

Turns the hydraulic measurements into the calibration-points CSV that
HydroBayesCal reads (``id, x, y, z, <QTY>_DATA, <QTY>_ERROR`` columns) and emits
a ``config_Telemac.py`` wiring the produced case to the calibration parameters
and BAL settings declared in the hydromate config.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from hydromate.config import Config
from hydromate import hydraulics

# map tidy measurement columns -> SELAFIN / HydroBayesCal quantity names
QUANTITY_COLUMN = {
    "WATER DEPTH": "water_depth",
    "SCALAR VELOCITY": "scalar_velocity",
}


def build_calibration_csv(cfg: Config) -> Path | None:
    """Write the calibration-points CSV from the measurements input."""
    if cfg.inputs.measurements is None:
        return None
    df = hydraulics.read_measurements(Path(cfg.inputs.measurements), cfg.crs_epsg)

    out = pd.DataFrame({
        "id": df["id"],
        "x": df["x"],
        "y": df["y"],
        "z": df.get("z", 0.0),
    })
    err = cfg.calibration.measurement_error
    for qty in cfg.calibration.calibration_quantities:
        col = QUANTITY_COLUMN.get(qty.upper())
        if col is None or col not in df.columns:
            raise ValueError(
                f"calibration quantity {qty!r} has no matching measurement column "
                f"(expected '{QUANTITY_COLUMN.get(qty.upper(), '?')}'). "
                f"Available: {[c for c in df.columns if c not in ('id', 'x', 'y', 'z')]}"
            )
        values = df[col].astype(float)
        out[f"{qty}_DATA"] = values
        out[f"{qty}_ERROR"] = (values.abs() * err).round(6)

    path = cfg.model_path(cfg.calibration_csv)
    out.to_csv(path, index=False)
    return path


def emit_hbc_config(cfg: Config, calibration_csv: Path | None) -> Path:
    """Emit a HydroBayesCal ``config_Telemac.py`` for the produced case."""
    c = cfg.calibration
    params = [p.name for p in c.parameters]
    ranges = [[p.min, p.max] for p in c.parameters]
    results_base = Path(cfg.results_slf).stem

    def pylist(items, q=True):
        if q:
            return "[" + ", ".join(repr(str(i)) for i in items) + "]"
        return "[" + ", ".join(str(i) for i in items) + "]"

    morph = ""
    if cfg.morphodynamics.enabled:
        morph = (
            "morphodynamic_simulation = {\n"
            f"    'gaia_cas': {cfg.gaia_cas!r},\n"
            f"    'gaia_results_filename_base': {cfg.morphodynamics.gaia_results_base!r},\n"
            "}\n\n"
        )

    text = f'''"""HydroBayesCal TELEMAC config generated by hydromate for case '{cfg.name}'.

Run a surrogate-assisted Bayesian calibration with:
    python bal_telemac.py --config {cfg.hbc_config}
"""

import os

BASE_DIR = {str(cfg.model_dir)!r}

paths = {{
    'case_template_dir': BASE_DIR,
    'model_dir': BASE_DIR,
    'res_dir': {str(cfg.results_dir)!r},
    'calibration_pts_file_path': {(str(calibration_csv) if calibration_csv else "")!r},
}}

hydrodynamic_simulation = {{
    'solver_name': 'Telemac2d',
    'n_processors': {cfg.telemac.n_processors},
    'results_filename_base': {results_base!r},
    'control_file': {cfg.cas_file!r},
    'friction_file': {cfg.friction_tbl!r},
    'fortran_file': None,
}}

{morph}calibration = {{
    'parameters': {pylist(params)},
    'param_values': {ranges},
    'extraction_quantities': {pylist(c.extraction_quantities)},
    'calibration_quantities': {pylist(c.calibration_quantities)},
    'dict_output_name': 'extraction-data',
}}

sampling = {{
    'init_runs': {c.init_runs},
    'max_runs': {c.max_runs},
    'parameter_distribution': 'uniform',
    'parameter_sampling_method': {c.parameter_sampling_method!r},
    'tp_selection_criteria': 'dkl',
    'eval_steps': 1,
    'prior_samples': 25000,
    'mc_samples_al': 2000,
    'mc_exploration': 1000,
    'gp_library': {c.gp_library!r},
}}

execution = {{
    'complete_bal_mode': True,
    'only_bal_mode': False,
    'delete_complex_outputs': True,
    'validation': False,
    'user_param_values': False,
}}
'''
    path = cfg.model_path(cfg.hbc_config)
    path.write_text(text)
    return path
