"""User configuration framework for the TELEMAC setup pipeline.

A single YAML file (see ``cases/example-Inn/case-config.yml``) describes the whole case: where the
TELEMAC environment lives, the coordinate system, the input geodata/hydraulics,
the meshing and friction strategy, and the calibration parameters handed to
HydroBayesCal. This module loads that YAML into validated dataclasses.

Design goals:
* one source of truth for paths so every stage agrees on file locations;
* sane defaults so a minimal YAML works, but every knob is overridable;
* fail loudly and early (missing inputs, inconsistent CRS) before TELEMAC runs.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field, fields
from pathlib import Path
from typing import Any

import yaml

log = logging.getLogger("hydromate")

# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def _resolve(base: Path, value: str | os.PathLike | None) -> Path | None:
    """Resolve *value* relative to *base* unless it is already absolute."""
    if value is None:
        return None
    p = Path(value)
    return p if p.is_absolute() else (base / p)


def _only_known(cls, data: dict[str, Any]) -> dict[str, Any]:
    """Drop keys that are not dataclass fields of *cls* (forward-compatible)."""
    known = {f.name for f in fields(cls)}
    unknown = set(data) - known
    if unknown:
        raise ValueError(f"{cls.__name__}: unknown config keys {sorted(unknown)}")
    return {k: v for k, v in data.items() if k in known}


# --------------------------------------------------------------------------- #
# sections
# --------------------------------------------------------------------------- #


@dataclass
class TelemacEnv:
    """How to reach and run the TELEMAC solver.

    ``pysource`` is the shell script that, when sourced, exports HOMETEL and the
    TELEMAC PYTHONPATH (e.g. ``configs/pysource.mint22.sh``). The pipeline does
    not import TELEMAC's Python directly; it sources this script in a subshell
    for any solver call (see :mod:`hydromate.env`).
    """

    pysource: Path
    solver: str = "telemac2d"  # telemac2d | telemac3d
    n_processors: int = 1
    version: str = "v8p4"

    def validate(self) -> None:
        if not Path(self.pysource).is_file():
            raise FileNotFoundError(
                f"TELEMAC pysource script not found: {self.pysource}. "
                "Set telemac.pysource to e.g. "
                "/home/schwindt/opt/telemac/configs/pysource.mint22.sh"
            )
        if self.solver not in ("telemac2d", "telemac3d"):
            raise ValueError(f"telemac.solver must be telemac2d|telemac3d, got {self.solver!r}")


@dataclass
class GroundTruthSource:
    """One raw ground-truth source to compile into the tidy measurements table.

    Measured values and their positions usually live in separate files: the
    *values* export (e.g. a SonTek FlowTracker ``.ft.sum`` workbook) and a
    *positions* point layer (shp/gpkg) joined on ``join_key``. ``category`` is the
    tab the source contributes to the tidy table (``hydraulics``, ``sediment``,
    ...); ``kind`` selects the adapter (``flowtracker`` or ``points``).
    """

    category: str
    kind: str = "flowtracker"            # flowtracker | points
    values: Path | None = None           # measured-values file (e.g. .ft.sum xlsx)
    positions: Path | None = None        # position layer (shp/gpkg) to join coords from
    join_key: str = "ID"


@dataclass
class CalibrationTargets:
    """The user-filled ``calibration-target-data.xlsx`` template and its links.

    ``file`` is the filled template (generated by ``hydromate targets``; tabs
    ``hydraulics`` / ``morphodynamics`` / ``parameters``). Measurement rows are
    joined by their unique ``join_key`` (default ``ID``) to the per-category
    point layers in ``user-sources/geodata/`` - ``hydraulics_positions`` and
    ``sediment_positions`` (reprojected to the project CRS on ingest); rows may
    instead carry explicit x/y, which win over the layer.
    """

    file: Path | None = None                  # filled calibration-target-data.xlsx
    hydraulics_positions: Path | None = None  # point layer for the hydraulics tab IDs
    sediment_positions: Path | None = None    # point layer for the morphodynamics tab IDs
    join_key: str = "ID"


@dataclass
class Geodata:
    """User-provided geodata files (paths resolved against the config dir).

    Pure geodata only - the boundary *conditions* (liquid boundary lines, inflow,
    rating curve, prescribed values) live in :class:`Boundaries`, and the
    calibration ground truth in :class:`GroundTruth`.
    """

    dem_initial: Path                    # baseline terrain (GeoTIFF)
    boundary: Path                       # ROI / max wetted extent polygon (shp/gpkg)
    dem_target: Path | None = None       # optional 2nd DEM for morphodynamic target
    breaklines: Path | None = None       # internal constraint lines (shp/gpkg)
    mesh_zones: Path | None = None       # polygons with a 'Zone Name' (channel/floodplain) for sizing
    channel_centerline: Path | None = None  # line the channel cells are elongated along
    roughness_zones: Path | None = None  # polygons with a 'Zone ID' for per-node roughness
    roughness_table: Path | None = None  # csv: zone_id, roughness (e.g. ks) -> calibrated by HBC
    region_points: Path | None = None    # seed points carrying MATID + max area
    region_table: Path | None = None     # region-pts-table.txt (MATID legend)
    dem_of_difference: Path | None = None  # precomputed DoD (else derived from DEMs)

    def validate(self) -> None:
        required = {"dem_initial": self.dem_initial, "boundary": self.boundary}
        missing = [name for name, p in required.items() if p is None or not Path(p).exists()]
        if missing:
            raise FileNotFoundError(f"Missing required geodata: {missing}")
        for name in ("dem_target", "breaklines", "mesh_zones", "channel_centerline",
                     "roughness_zones", "roughness_table", "region_points",
                     "region_table", "dem_of_difference"):
            p = getattr(self, name)
            if p is not None and not Path(p).exists():
                raise FileNotFoundError(f"geodata.{name} set but not found: {p}")


@dataclass
class Boundaries:
    """Boundary conditions: the liquid-boundary lines plus the prescribed values.

    ``liquid_boundaries`` is the LINE layer whose 'Type (inflow/outflow)' field
    tags each line; it is required for a build. ``inflow`` (a discharge time series
    CSV) is OPTIONAL - it drives a later *unsteady* case; the steady initial run is
    driven by the scalar ``prescribed_flowrate`` (and ``prescribed_elevation`` /
    ``stage_discharge`` for the outflow).
    """

    liquid_boundaries: Path | None = None  # inflow/outflow boundary lines (shp/gpkg)
    inflow: Path | None = None           # discharge time series (csv); optional, for unsteady
    stage_discharge: Path | None = None  # outlet rating curve (csv), for outflow_condition=stage_discharge
    # downstream (outflow) boundary type:
    #   "elevation"       -> prescribed water level (cli 5 4 4) from prescribed_elevation (default)
    #   "stage_discharge" -> prescribed water level (cli 5 4 4) read from stage_discharge at Q
    #   "free"            -> Neumann / free outflow (cli 4 4 4), nothing prescribed
    outflow_condition: str = "elevation"
    prescribed_flowrate: float | None = None   # upstream Q (m3/s) for the steady run
    prescribed_elevation: float | None = None  # downstream WSE (m) for outflow_condition=elevation

    def validate(self) -> None:
        if self.liquid_boundaries is None or not Path(self.liquid_boundaries).exists():
            raise FileNotFoundError(
                f"boundaries.liquid_boundaries not found: {self.liquid_boundaries}"
            )
        for name in ("inflow", "stage_discharge"):
            p = getattr(self, name)
            if p is not None and not Path(p).exists():
                raise FileNotFoundError(f"boundaries.{name} set but not found: {p}")
        if self.outflow_condition not in ("stage_discharge", "elevation", "free"):
            raise ValueError(
                "boundaries.outflow_condition must be 'stage_discharge', 'elevation', "
                f"or 'free', got {self.outflow_condition!r}"
            )


@dataclass
class Initialization:
    """Initial-condition controls for the run (dry start vs pre-wetting)."""

    initial_conditions: str = "ZERO DEPTH"
    # DRY START (the default): a fully dry bed makes TELEMAC's DEBIMP abort at a
    # prescribed-Q inflow, so instead we seed only a thin water plug on the nodes
    # within dry_start_extent of the inflow line(s) - deep enough (dry_start_depth,
    # kept >= the normal depth so the inflow stays subcritical) for the discharge to
    # establish - and leave the rest of the domain DRY. The flow then wets the reach.
    dry_start_depth: float = 0.5          # inflow-plug seed depth [m]
    dry_start_extent: float | None = None  # plug buffer around the inflow line [m]; default ~5 cells
    # pre-wetting (hotstart): when set, instead of the dry start above, seed this
    # water depth (m) on the *channel mesh-zone* nodes (dry elsewhere) and continue
    # from it - wets the whole low-flow channel up front (the mesh-convergence study
    # uses it to skip advancing the wetting front per mesh). Needs geodata.mesh_zones.
    prewet_depth: float | None = None


@dataclass
class GroundTruth:
    """Calibration ground truth: a tidy measurements table or raw sources to compile.

    Provide either ``measurements`` (a user-authored tidy multi-tab table) or
    ``sources`` (raw sources hydromate compiles into that table). When ``sources``
    are given, ``measurements`` (if set) is the compiled artifact's output path.
    """

    measurements: Path | None = None     # tidy multi-tab ground-truth table (xlsx/csv)
    sources: list[GroundTruthSource] = field(default_factory=list)  # raw sources to compile
    targets: CalibrationTargets | None = None  # filled calibration-target-data.xlsx

    def problems(self) -> list[str]:
        """Return ground-truth input problems as messages (empty when all OK).

        Ground truth feeds only the *calibration / HydroBayesCal* setup (pipeline
        stage 5), never the TELEMAC model build itself, so a missing or mismatched
        source must NOT abort the build. Callers treat these as warnings: the model
        setup still completes and only the HydroBayesCal setup is skipped.
        """
        issues: list[str] = []
        # measurements is a user-authored tidy table only when no raw sources /
        # targets are given (otherwise it is the artifact compiled from them).
        if self.measurements is not None and not self.sources \
                and self.targets is None \
                and not Path(self.measurements).exists():
            issues.append(
                f"ground_truth.measurements set but not found: {self.measurements}"
            )
        for src in self.sources:
            for field_name in ("values", "positions"):
                p = getattr(src, field_name)
                if p is not None and not Path(p).exists():
                    issues.append(
                        f"ground_truth source '{src.category}' {field_name} not found: {p}"
                    )
        if self.targets is not None:
            for field_name in ("file", "hydraulics_positions", "sediment_positions"):
                p = getattr(self.targets, field_name)
                if p is not None and not Path(p).exists():
                    issues.append(
                        f"ground_truth.targets.{field_name} set but not found: {p}"
                    )
        return issues


@dataclass
class MeshConfig:
    """gmsh meshing controls.

    Two strategies, chosen automatically:

    * **Anisotropic, flow-aligned** (preferred) - when ``geodata.mesh_zones`` and
      ``geodata.channel_centerline`` are given. Each mesh-zone polygon is classified
      by its ``Zone Name`` (substring, case-insensitive) into one of three types and
      sized by its own ``Max Edge Length (m)`` field (``zone_size_field``; the
      ``*_size`` values below are only fallbacks when that field is absent/blank):
      ``channel`` zones get triangles elongated along the centerline (cross-channel
      edge = the zone's max edge length, stretched by ``channel_anisotropy`` along
      the flow); ``floodplain`` zones get near-equilateral triangles of the zone's
      edge length; ``refinement`` zones get near-equilateral triangles at their
      (typically smaller) edge length for **local refinement**. The size grows
      between zones at ``growth_ratio`` per element. Where zones overlap the finest
      intent wins (refinement > channel > floodplain). Implemented with a
      metric-tensor background mesh and gmsh's BAMG algorithm.
    * **Isotropic fallback** - ``default_size`` everywhere, refined to
      ``breakline_size`` along breaklines and per-MATID via ``region_sizes``.

    ``region_sizes`` maps a MATID (as int) to a target maximum element edge
    length (m); it mirrors the 'max_area' intent of region-pts-table.txt but in
    edge-length terms used by gmsh size fields.
    """

    # global multiplier on EVERY target edge length below, including the per-zone
    # `Max Edge Length (m)` values read from the mesh_zones gpkg (which otherwise
    # silently override the *_size fallbacks). The mesh-convergence study varies
    # this to coarsen/refine the whole sizing field uniformly.
    size_scale: float = 1.0

    # anisotropic, flow-aligned strategy (channel/floodplain zones + centerline)
    channel_size: float = 0.5           # channel edge length (m); fallback if not in the gpkg
    floodplain_size: float = 1.5        # floodplain edge length (m); also the default outside zones
    refinement_size: float = 0.5        # 'refinement' zone edge length (m); fallback if not in the gpkg
    growth_ratio: float = 1.2           # max edge-size growth per element (channel->floodplain)
    channel_anisotropy: float = 4.0     # along-flow / cross-flow edge ratio in the channel
    max_aspect_ratio: float = 4.0       # hard cap on cell aspect ratio (gmsh Mesh.AnisoMax)
    zone_name_field: str = "Zone Name"  # attribute in mesh_zones naming each zone
    # per-polygon max edge length [m] in mesh_zones (overrides the *_size defaults
    # above); read with a decimal-comma-tolerant parser so a German-locale gpkg works
    zone_size_field: str = "Max Edge Length (m)"
    roughness_zone_field: str = "Zone ID"  # integer-id attribute in roughness_zones

    # quality-report thresholds (warnings only; channel anisotropy is exempt)
    min_angle_deg: float = 30.0         # warn if floodplain cells dip below this
    max_angle_deg: float = 90.0         # warn on obtuse floodplain cells above this
    max_area_jump: float = 0.20         # warn on adjacent-cell area jumps over this (20%)

    # isotropic fallback strategy
    default_size: float = 10.0          # background target edge length (m)
    breakline_size: float = 3.0         # refined size along breaklines (m)
    region_sizes: dict[int, float] = field(default_factory=dict)
    min_size: float = 0.5
    grow_rate: float = 1.3              # gmsh Mesh.MeshSizeFromCurvature growth
    algorithm: int = 5                 # gmsh 2D algo (5 = Delaunay)


@dataclass
class FrictionZone:
    """A bed-friction zone tied to a MATID, the calibration target for TELEMAC."""

    matid: int
    name: str
    law: int = 4                       # 4 = Manning
    coefficient: float = 0.03          # initial value; perturbed by HydroBayesCal


@dataclass
class Friction:
    default_law: int = 4               # Manning
    default_coefficient: float = 0.03
    # law for the .tbl rows derived from geodata.roughness_zones + roughness_table
    # (5 = NIKU, Nikuradse k_s in metres - matching the ks roughness values)
    roughness_law: int = 5
    # lateral (wall) boundary friction -> TELEMAC LAW OF FRICTION ON LATERAL
    # BOUNDARIES / ROUGHNESS COEFFICIENT OF BOUNDARIES (3 = Strickler, 4 = Manning)
    boundary_law: int = 4
    boundary_coefficient: float = 0.03
    zones: list[FrictionZone] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Friction":
        zones = [FrictionZone(**_only_known(FrictionZone, z)) for z in d.get("zones", [])]
        return cls(
            default_law=d.get("default_law", 4),
            default_coefficient=d.get("default_coefficient", 0.03),
            roughness_law=d.get("roughness_law", 5),
            boundary_law=d.get("boundary_law", 4),
            boundary_coefficient=d.get("boundary_coefficient", 0.03),
            zones=zones,
        )


@dataclass
class Hydrodynamics:
    """Telemac2d steering knobs and prescribed boundary values."""

    regime: str = "steady"             # steady | unsteady
    # initial / maximum step. With variable_timestep on, TELEMAC shrinks it to hold
    # DESIRED COURANT NUMBER, so this is only the conservative starting step (0.25 s
    # keeps the first transient stable on a dry/wetting bed); the Courant target drives
    # the marching step thereafter.
    time_step: float = 0.25
    n_time_steps: int = 15000          # caps a FIXED-step run; for the variable-step run see duration
    # total simulated time [s] for the steady (variable-timestep) march. When None it
    # falls back to n_time_steps * time_step. Set it explicitly so the simulated
    # duration is decoupled from the (small) CFL start step above.
    duration: float | None = None
    graphic_printout_period: int = 500
    listing_printout_period: int = 500
    # OPT-IN steady-state auto-stop (TELEMAC's STOP IF A STEADY STATE IS REACHED).
    # OFF by default because it is UNRELIABLE with the variable time step: TELEMAC's
    # steady.f compares two CONSECUTIVE TIME STEPS with an ABSOLUTE per-step threshold
    # (|H - H_prev| < stop_criteria etc.), and the CFL-driven dt is tiny, so during a
    # slow transient (e.g. a low-discharge reach still filling from a dry start) the
    # per-step change drops below 1.E-4 m long before the boundary fluxes balance -
    # halting the run far from steady state. Convergence is judged instead by the
    # boundary-flux balance (hydromate.flux_convergence). Enable this only with a
    # FIXED time step (variable_timestep: false), where a per-step change is meaningful.
    # stop_criteria order is H ; (U,V) ; tracers (TELEMAC's steady.f; the dico's English
    # help listing (U,V) first is wrong) - absolute changes in m, m/s, tracer units.
    stop_if_steady: bool = False
    stop_criteria: str = "1.E-4;1.E-4;1.E-4"   # absolute per-step change: H; (U,V); tracers
    # let TELEMAC adapt the time step to the CFL condition (DESIRED COURANT NUMBER):
    # a fixed time_step on a fine channel mesh (sub-metre cells) is a CFL violation
    # that diverges; with this on, time_step is only the initial/maximum step.
    # 0.6 is a conservative, stable target on the fine channel mesh (matching the 3D
    # run); raise it toward ~0.9 to march to steady state in fewer steps, or raise
    # n_time_steps if a run has not converged within the budget.
    variable_timestep: bool = True
    # 0.30 is a conservative, explosion-safe Courant target for the wetting/drying
    # steady march with k-epsilon on the fine channel mesh; raise it toward ~0.6-0.9
    # to reach steady state in fewer steps once a case is known to be stable.
    desired_courant: float = 0.30
    # discretisation: the classic finite-element kernel is the DEFAULT - it supports
    # the k-epsilon / Spalart-Allmaras / Smagorinski turbulence closures auto-selected
    # by turbulence_model below (the solver/* and tidal-flats keywords then apply).
    # Set finite_volumes=True for the HLLC finite-volume kernel instead - robust for
    # transcritical wetting/drying flow on steep terrain, but it accepts ONLY
    # turbulence model 1 (constant viscosity). finite_volume_scheme 5 = HLLC Riemann
    # solver, fv_space_order 2 = 2nd-order (MUSCL).
    finite_volumes: bool = False
    finite_volume_scheme: int = 5      # 0 Roe, 1 kinetic, 3 Zokagoa, 4 Tchamen, 5 HLLC, 6 WAF
    fv_space_order: int = 2
    # 0.9 strongly damps free-surface wiggles over steep bed gradients (FE; TELEMAC
    # default 1.0). Lower values (e.g. 0.1) under-damp and let the surface oscillate
    # into divergence on the high-aspect channel mesh.
    free_surface_gradient_compat: float = 0.9
    # FE advection robustness for the distributive velocity scheme (14):
    #   implicitation 0.80 -> more implicit (stable) depth/velocity update (TELEMAC
    #     default 0.55, which is too explicit for the wetting front here);
    #   discretizations_in_space "11;11" -> LINEAR elements for H and U,V, required so
    #     the distributive scheme 14 is not rejected ("DISTRIBUTIVE SCHEMES NOT
    #     IMPLEMENTED FOR QUASI-BULLE AND QUADRATIC ELEMENTS");
    #   advection_sub_iterations / max_advection_iterations -> non-linearity sub-cycles
    #     and the per-step advection solve budget that keep the scheme converging.
    implicitation: float = 0.80
    discretizations_in_space: str = "11;11"
    advection_sub_iterations: int = 2       # NUMBER OF SUB-ITERATIONS FOR NON-LINEARITIES
    max_advection_iterations: int = 100     # MAXIMUM NUMBER OF ITERATIONS FOR ADVECTION SCHEMES
    # keep H unclipped (H CLIPPING : NO) so the tidal-flat / negative-depth treatment,
    # not a hard clip, handles drying - clipping H injects mass and destabilises the
    # wetting front. Set True only to hard-floor the depth as a last resort.
    h_clipping: bool = False
    # finite-element linear solver: 2 = preconditioned CG (robust where plain CG,
    # solver 1, stalls); preconditioning 2 = diagonal; solver_accuracy = tolerance.
    solver: int = 2
    preconditioning: int = 2
    solver_accuracy: float = 1.0e-5
    # turbulence-transport solver accuracy (ACCURACY OF K / EPSILON / SPALART-ALLMARAS):
    # TELEMAC's 1e-9 default is far tighter than the turbulence quantities need and is
    # unreachable within the 50-iteration cap while the dry-start domain is still
    # ill-conditioned - that is the transient "GRACJG: EXCEEDING MAXIMUM ITERATIONS 50"
    # warning. 1e-6 converges quickly (fewer iterations) with no loss of meaning.
    turbulence_solver_accuracy: float = 1.0e-6
    # solve budget for the k-epsilon step (MAXIMUM NUMBER OF ITERATIONS FOR K AND
    # EPSILON). TELEMAC's default 50 is too few while the dry-start domain is still
    # ill-conditioned; 120 lets the turbulence solve converge without relaxing accuracy.
    max_keps_iterations: int = 120
    # turbulence closure. "auto" (the default) picks among k-epsilon (3),
    # Spalart-Allmaras (6) and Smagorinski LES (4) from the channel mesh resolution
    # relative to the turbulence length scale (the flow depth) and the velocity guess
    # below, applying the 80%-TKE LES criterion - see steering.select_turbulence_model.
    # A literal int or name (1 const-visc, 3 k-epsilon, 4 Smagorinski, 6
    # Spalart-Allmaras) overrides the auto choice. NOTE: finite volumes accept ONLY
    # model 1; "auto"/3/4/6 require finite_volumes=False (the default kernel).
    turbulence_model: int | str = "auto"
    # mean-flow velocity guess [m/s] - the assumed initial average flow used to size
    # the turbulent eddy viscosity and feed the turbulence-model selection criteria.
    initial_velocity_guess: float = 1.0
    # turbulence integral length scale [m] for the resolution criterion; defaults to
    # the flow depth scale (prewet_depth, else 1.0 m) when left None.
    turbulence_length_scale: float | None = None
    velocity_diffusivity: float | None = None   # eddy viscosity [m2/s]; auto from U for model 1
    extra_keywords: dict[str, Any] = field(default_factory=dict)  # raw .cas overrides


@dataclass
class Morphodynamics:
    """GAIA morphodynamic block - extension point, off by default in v1.

    Two transport modes, independently toggleable and combinable (a GAIA run may do
    bedload only, suspension only, or both):

    * ``bedload`` -> ``BED LOAD FOR ALL SANDS : YES`` with
      ``BED-LOAD TRANSPORT FORMULA FOR ALL SANDS : bedload_formula`` in the GAIA
      steering file (1 = Meyer-Peter & Mueller).
    * ``suspended_load`` -> ``SUSPENSION FOR ALL SANDS : YES``; GAIA then transports
      the suspended sediment classes as TELEMAC **tracers** (no manual NUMBER OF
      TRACERS on the hydro side - GAIA declares them through the coupling).

    When ``enabled`` the hydrodynamic ``.cas`` gets ``COUPLING WITH : 'GAIA'`` +
    ``GAIA STEERING FILE`` and a ``COUPLING PERIOD FOR GAIA`` (hydro steps per GAIA
    step). The coupling is wired into **every** hydrodynamic run that can carry it -
    the steady ``steady2d.cas`` and, most usefully for morphodynamics, the
    hydrograph-driven ``unsteady2d.cas`` and its 3D twin ``unsteady3d.cas`` (a flood
    wave is what actually reworks the bed), so the same GAIA steering file drives 2D
    and 3D bed evolution.

    Beyond the two transport switches, the block exposes the bed-process capacities a
    real river morphodynamic run needs, all mapped to verified GAIA keywords:

    * ``morphological_factor`` -> ``MORPHOLOGICAL FACTOR`` - scales the bed evolution
      per hydraulic step so a long morphological response can be reached within a
      shorter hydrograph (1.0 = no acceleration).
    * ``slope_effect`` / ``slope_formula`` / ``friction_angle`` -> ``SLOPE EFFECT`` +
      ``FORMULA FOR SLOPE EFFECT`` (1 = Koch & Flokstra) + ``FRICTION ANGLE OF THE
      SEDIMENT`` [deg] - the gravitational pull that steers bedload down transverse
      bed slopes (bank erosion, bar shaping).
    * ``secondary_currents`` / ``secondary_currents_alpha`` -> ``SECONDARY CURRENTS``
      + ``SECONDARY CURRENTS ALPHA COEFFICIENT`` - the spiral-flow deviation of
      bedload in bends (relevant for a meandering reach).
    * ``bed_layers`` / ``active_layer_thickness`` -> ``NUMBER OF LAYERS FOR INITIAL
      STRATIFICATION`` + ``ACTIVE LAYER THICKNESS`` [m] - the bed stratigraphy for
      graded sediment / hiding.
    * ``prescribed_solid_discharges`` -> ``PRESCRIBED SOLID DISCHARGES`` [m3/s], one
      value per liquid boundary in the driver's FRONT2 order (0 = no supply /
      free-outflow; ``None`` = GAIA's equilibrium sediment inflow).
    * ``sediment_type`` -> ``CLASSES TYPE OF SEDIMENT`` (``NCO`` non-cohesive /
      ``CO`` cohesive), ``mass_balance`` -> ``MASS-BALANCE`` (log the sediment
      budget), ``graphic_printouts`` -> the GAIA ``VARIABLES FOR GRAPHIC PRINTOUTS``.
    """

    enabled: bool = False
    bedload: bool = True                 # BED LOAD FOR ALL SANDS : YES
    suspended_load: bool = False         # SUSPENSION FOR ALL SANDS : YES (carried as tracers)
    bedload_formula: int = 1             # BED-LOAD TRANSPORT FORMULA (1 = Meyer-Peter & Mueller)
    coupling_period: int = 1             # COUPLING PERIOD FOR GAIA (hydro steps per GAIA step)
    gaia_results_base: str = "rgaia"
    sediment_classes: list[dict[str, Any]] = field(default_factory=list)
    # --- bed-process capacities (all verified GAIA keywords; safe defaults) ---
    sediment_type: str = "NCO"           # CLASSES TYPE OF SEDIMENT (NCO non-cohesive / CO cohesive)
    morphological_factor: float = 1.0    # MORPHOLOGICAL FACTOR (bed-evolution acceleration)
    slope_effect: bool = True            # SLOPE EFFECT (transverse bed-slope pull on bedload)
    slope_formula: int = 1               # FORMULA FOR SLOPE EFFECT (1 = Koch & Flokstra)
    friction_angle: float = 40.0         # FRICTION ANGLE OF THE SEDIMENT [deg]
    secondary_currents: bool = False     # SECONDARY CURRENTS (spiral-flow bedload deviation in bends)
    secondary_currents_alpha: float = 1.0  # SECONDARY CURRENTS ALPHA COEFFICIENT
    bed_layers: int = 1                  # NUMBER OF LAYERS FOR INITIAL STRATIFICATION
    active_layer_thickness: float | None = None  # ACTIVE LAYER THICKNESS [m]; None -> GAIA default
    prescribed_solid_discharges: list[float] | None = None  # per liquid boundary (FRONT2 order)
    mass_balance: bool = True            # MASS-BALANCE (log the sediment budget)
    graphic_printouts: str | None = None  # GAIA VARIABLES FOR GRAPHIC PRINTOUTS; None -> default set
    extra_keywords: dict[str, Any] = field(default_factory=dict)


@dataclass
class DemOfDifference:
    """DEM-of-Difference (DoD) computation with a minimum level of detection (LoD).

    When ``enabled``, stage 1 computes the bed-change raster
    ``dem_target - dem_initial`` on the ROI-clipped initial grid (so the DoD is
    inherently clipped to ``geodata.boundary``) and applies a **minimum level of
    detection** (minLoD) - the survey-uncertainty floor below which a difference is
    indistinguishable from noise. Cells with ``|dz| < LoD`` are either masked to
    nodata (``mask_below_lod: true``, the default) or set to 0.

    The LoD [m] is resolved, in priority order, from:

    * an explicit ``min_lod`` (a fixed threshold you already trust), else
    * the **propagated survey uncertainty**
      ``LoD = t * sqrt(uncertainty_initial^2 + uncertainty_target^2)`` where each
      ``uncertainty_*`` is that DEM's vertical error (1-sigma, m) and ``t`` is the
      two-tailed critical value for ``confidence_level`` (0.95 -> 1.96), the
      best-available spatially-uniform propagated-error method (Brasington/Wheaton),
      else
    * 0 (report the raw difference, no thresholding) when neither is given.
    """

    enabled: bool = False
    uncertainty_initial: float | None = None   # vertical 1-sigma error of dem_initial [m]
    uncertainty_target: float | None = None    # vertical 1-sigma error of dem_target [m]
    confidence_level: float = 0.95             # two-tailed -> t/z critical value for the propagated LoD
    min_lod: float | None = None               # explicit minimum LoD [m]; overrides the propagated value
    mask_below_lod: bool = True                # |dz| < LoD -> nodata (True) or 0.0 (False)
    output: str = "dem-of-difference.tif"      # output filename in preprocessing_dir

    def validate(self) -> None:
        if not self.enabled:
            return
        if not 0.0 < self.confidence_level < 1.0:
            raise ValueError(
                "dem_of_difference.confidence_level must be in (0, 1), got "
                f"{self.confidence_level}"
            )
        for name in ("uncertainty_initial", "uncertainty_target", "min_lod"):
            v = getattr(self, name)
            if v is not None and v < 0.0:
                raise ValueError(f"dem_of_difference.{name} must be >= 0, got {v}")


@dataclass
class CalibrationParameter:
    """One calibration parameter forwarded to HydroBayesCal.

    ``name`` must follow HydroBayesCal's prefix convention:
    ``zone<N>`` (friction), ``gaia<KEYWORD> <class>`` (GAIA), ``vg_zone...``
    (vegetation), ``f.<name>`` (Fortran) or a literal TELEMAC keyword.
    """

    name: str
    min: float
    max: float
    comment: str = ""


@dataclass
class Calibration:
    parameters: list[CalibrationParameter] = field(default_factory=list)
    calibration_quantities: list[str] = field(default_factory=lambda: ["WATER DEPTH"])
    extraction_quantities: list[str] = field(
        default_factory=lambda: ["WATER DEPTH", "SCALAR VELOCITY"]
    )
    measurement_error: float = 0.10    # fraction of measured value
    # BAL / sampling settings (passed through to config_Telemac.py)
    init_runs: int = 30
    max_runs: int = 50
    parameter_sampling_method: str = "sobol"
    gp_library: str = "gpy"
    # HydroBayesCal predicts the surrogate at prior_samples points by building a
    # (prior_samples x prior_samples) dense covariance PER calibration location in
    # gpytorch; 25000 OOM-kills a 16 GB box. A low-dimensional roughness posterior
    # needs only a few thousand - 5000 is ample and memory-safe. Raise with RAM.
    prior_samples: int = 5000

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Calibration":
        params = [CalibrationParameter(**_only_known(CalibrationParameter, p))
                  for p in d.get("parameters", [])]
        rest = {k: v for k, v in d.items() if k != "parameters"}
        return cls(parameters=params, **_only_known(cls, rest))


# --------------------------------------------------------------------------- #
# top-level config
# --------------------------------------------------------------------------- #


@dataclass
class Config:
    name: str
    crs_epsg: int
    config_dir: Path
    # all produced artifacts live under hydromate-case/, split by workflow phase
    preprocessing_dir: Path   # preprocessing.py products (DEM clips, meshes, ground truth)
    model_dir: Path           # the TELEMAC case (build): geometry/cli/cas/tbl + results
    postprocessing_dir: Path  # mesh-convergence study and other post-processing
    calibration_dir: Path     # HydroBayesCal artifacts (calibration CSV, config_Telemac.py)
    telemac: TelemacEnv
    geodata: Geodata
    boundaries: Boundaries
    initialization: Initialization
    mesh: MeshConfig
    friction: Friction
    hydrodynamics: Hydrodynamics
    morphodynamics: Morphodynamics
    ground_truth: GroundTruth
    calibration: Calibration
    # DoD computation (optional; disabled by default so existing cases are unaffected)
    dem_of_difference: DemOfDifference = field(default_factory=DemOfDifference)

    # canonical output filenames inside model_dir -----------------------------
    geometry_slf: str = "geometry.slf"
    boundary_cli: str = "boundaries.cli"
    cas_file: str = "steady2d.cas"           # the initial run - always steady
    # additional hydrograph-driven run, written only when the inflow carries a
    # varying time series (otherwise a constant-Q inflow needs no unsteady case)
    unsteady_cas_file: str = "unsteady2d.cas"
    liquid_boundaries_file: str = "inflow-hydrograph.liq"  # Q(t)/SL(t) for unsteady2d.cas
    # serialized FRONT2-ordered LiquidBoundary list written during the build, so the
    # standalone unsteady / 3D scripts get the boundary numbering without re-meshing
    liquid_boundaries_json: str = "liquid-boundaries.json"
    control_sections_file: str = "control-sections.txt"    # unsteady flux-verification sections
    sections_output_file: str = "r-control-sections.txt"   # SECTIONS OUTPUT FILE
    results_unsteady_slf: str = "r2d-unsteady.slf"         # unsteady2d.cas RESULTS FILE
    results3d_unsteady_slf: str = "r3d-unsteady.slf"       # unsteady telemac3d 3D RESULT FILE
    results2d_from_3d_unsteady_slf: str = "r3d-2d-unsteady.slf"  # unsteady 3D 2D RESULT FILE
    ic_slf: str = "initial-conditions.slf"   # hotstart file when prewet_depth is set
    friction_tbl: str = "friction.tbl"
    zones_file: str = "zones.bfr"
    gaia_cas: str = "gaia.cas"
    results_slf: str = "r2d.slf"
    results3d_slf: str = "r3d.slf"          # TELEMAC-3D 3D RESULT FILE (add3d.py)
    results2d_from_3d_slf: str = "r3d-2d.slf"  # TELEMAC-3D depth-averaged 2D RESULT FILE
    ground_truth_xlsx: str = "ground-truth.xlsx"  # compiled tidy table (in preprocessing_dir)
    calibration_csv: str = "measurements-calibration.csv"
    hbc_config: str = "config_Telemac.py"
    # per-phase compound logfile name; each script logs into its own output folder
    log_file: str = "hydromate.log"

    def preprocessing_path(self, filename: str) -> Path:
        return Path(self.preprocessing_dir) / filename

    def model_path(self, filename: str) -> Path:
        return Path(self.model_dir) / filename

    def postprocessing_path(self, filename: str) -> Path:
        return Path(self.postprocessing_dir) / filename

    def calibration_path(self, filename: str) -> Path:
        return Path(self.calibration_dir) / filename

    @property
    def ground_truth_path(self) -> Path:
        """Where the tidy ground-truth table lives (explicit input, else compiled)."""
        if self.ground_truth.measurements is not None:
            return Path(self.ground_truth.measurements)
        return self.preprocessing_path(self.ground_truth_xlsx)

    def validate(self) -> None:
        self.telemac.validate()
        self.geodata.validate()
        self.boundaries.validate()
        # ground truth is non-fatal: it feeds only the calibration/HydroBayesCal
        # setup, so a missing/mismatched source warns and skips that setup rather
        # than aborting the model build (see GroundTruth.problems / pipeline stage 5).
        for problem in self.ground_truth.problems():
            log.warning("%s; HydroBayesCal setup will be skipped", problem)
        cond = self.boundaries.outflow_condition
        if cond == "stage_discharge" and self.boundaries.stage_discharge is None:
            raise ValueError(
                "outflow_condition: stage_discharge requires boundaries.stage_discharge "
                "(a Q-h rating CSV alongside the config). Generate one from a "
                "Manning/Strickler value and channel geometry with `hydromate rating`."
            )
        if cond == "elevation" and self.boundaries.prescribed_elevation is None:
            raise ValueError(
                "outflow_condition: elevation requires boundaries.prescribed_elevation"
            )
        if self.initialization.prewet_depth is not None and self.geodata.mesh_zones is None:
            raise ValueError(
                "initialization.prewet_depth needs geodata.mesh_zones (with a "
                "'*channel*' Zone Name) to define the region to pre-wet."
            )
        if self.morphodynamics.enabled and self.geodata.dem_target is None \
                and self.geodata.dem_of_difference is None:
            raise ValueError(
                "morphodynamics.enabled but no geodata.dem_target / dem_of_difference "
                "provided for topographic-change calibration data."
            )
        self.dem_of_difference.validate()
        if self.dem_of_difference.enabled and self.geodata.dem_target is None \
                and self.geodata.dem_of_difference is None:
            raise ValueError(
                "dem_of_difference.enabled but no geodata.dem_target (to difference "
                "against geodata.dem_initial) nor a precomputed geodata.dem_of_difference."
            )

    def ensure_dirs(self) -> None:
        for d in (self.preprocessing_dir, self.model_dir,
                  self.postprocessing_dir, self.calibration_dir):
            Path(d).mkdir(parents=True, exist_ok=True)


def load_config(path: str | os.PathLike) -> Config:
    """Load and validate a YAML config into a :class:`Config`."""
    path = Path(path).resolve()
    cfg_dir = path.parent
    with open(path) as fh:
        raw = yaml.safe_load(fh) or {}

    project = raw.get("project", {})
    sim_dir = project.get("sim_dir", "hydromate-case")
    # per-phase output dirs under hydromate-case/ (older work_dir/results_dir accepted)
    preprocessing_dir = _resolve(
        cfg_dir, project.get("preprocessing_dir") or project.get("work_dir")
        or f"{sim_dir}/preprocessing")
    model_dir = _resolve(cfg_dir, project.get("model_dir") or f"{sim_dir}/simulation")
    postprocessing_dir = _resolve(
        cfg_dir, project.get("postprocessing_dir") or f"{sim_dir}/postprocessing")
    calibration_dir = _resolve(
        cfg_dir, project.get("calibration_dir") or project.get("results_dir")
        or f"{sim_dir}/calibration-validation")

    # telemac env
    tdict = dict(raw.get("telemac", {}))
    tdict["pysource"] = _resolve(cfg_dir, tdict.get("pysource"))
    telemac = TelemacEnv(**_only_known(TelemacEnv, tdict))

    # geodata (resolve every path against the config dir)
    gdict = dict(raw.get("geodata") or {})
    for key in list(gdict):
        gdict[key] = _resolve(cfg_dir, gdict[key])
    geodata = Geodata(**_only_known(Geodata, gdict))

    # boundaries: liquid-boundary lines / inflow / rating are paths; the rest scalars
    bdict = dict(raw.get("boundaries") or {})
    for key in ("liquid_boundaries", "inflow", "stage_discharge"):
        if key in bdict:
            bdict[key] = _resolve(cfg_dir, bdict[key])
    boundaries = Boundaries(**_only_known(Boundaries, bdict))

    initialization = Initialization(
        **_only_known(Initialization, raw.get("initialization", {}) or {}))

    # ground truth: a compiled/authored measurements table + raw sources to compile
    gtdict = dict(raw.get("ground_truth") or {})
    gt_raw = gtdict.pop("sources", None) or []
    measurements = _resolve(cfg_dir, gtdict.get("measurements"))
    sources = []
    for src in gt_raw:
        src = _only_known(GroundTruthSource, src)
        src["values"] = _resolve(cfg_dir, src.get("values"))
        src["positions"] = _resolve(cfg_dir, src.get("positions"))
        sources.append(GroundTruthSource(**src))
    targets = None
    tdict = gtdict.get("targets")
    if tdict:
        tdict = _only_known(CalibrationTargets, dict(tdict))
        for key in ("file", "hydraulics_positions", "sediment_positions"):
            if key in tdict:
                tdict[key] = _resolve(cfg_dir, tdict[key])
        targets = CalibrationTargets(**tdict)
    ground_truth = GroundTruth(measurements=measurements, sources=sources,
                               targets=targets)

    mesh = MeshConfig(**_only_known(MeshConfig, raw.get("mesh", {}) or {}))
    # YAML maps keys may come back as str; coerce region_sizes keys to int
    mesh.region_sizes = {int(k): float(v) for k, v in (mesh.region_sizes or {}).items()}

    friction = Friction.from_dict(raw.get("friction", {}) or {})
    hydro = Hydrodynamics(**_only_known(Hydrodynamics, raw.get("hydrodynamics", {}) or {}))
    morph = Morphodynamics(**_only_known(Morphodynamics, raw.get("morphodynamics", {}) or {}))
    dod = DemOfDifference(
        **_only_known(DemOfDifference, raw.get("dem_of_difference", {}) or {}))
    calib = Calibration.from_dict(raw.get("calibration", {}) or {})

    cfg = Config(
        name=project.get("name", path.stem),
        crs_epsg=int(project.get("crs_epsg", 25832)),
        config_dir=cfg_dir,
        preprocessing_dir=preprocessing_dir,
        model_dir=model_dir,
        postprocessing_dir=postprocessing_dir,
        calibration_dir=calibration_dir,
        telemac=telemac,
        geodata=geodata,
        boundaries=boundaries,
        initialization=initialization,
        mesh=mesh,
        friction=friction,
        hydrodynamics=hydro,
        morphodynamics=morph,
        ground_truth=ground_truth,
        calibration=calib,
        dem_of_difference=dod,
    )
    # apply optional output-filename overrides
    for key, value in (raw.get("outputs", {}) or {}).items():
        if hasattr(cfg, key):
            setattr(cfg, key, value)
    return cfg
