"""Stage 4 — steering files: friction ``.tbl`` and the TELEMAC ``.cas`` (+ GAIA stub).

The friction table lists one row per MATID zone (``<id> <LAW> <coef> NULL``,
terminated by ``END``); node-to-zone linkage is carried by the ``FRIC_ID``
variable in the geometry SELAFIN (written in stage 2). HydroBayesCal perturbs the
coefficient column of this table during calibration.

The ``.cas`` is assembled from a small set of building blocks plus user overrides
so the case is reproducible and the prescribed boundary values stay consistent
with the liquid-boundary numbering from stage 3.
"""

from __future__ import annotations

from pathlib import Path

from hydromate.config import Config
from hydromate.boundary import LiquidBoundary

# friction-law number -> 4-letter name used in the .tbl
LAW_NAMES = {0: "NOFR", 1: "HAAL", 2: "CHEZ", 3: "STRI", 4: "MANN", 5: "NIKU", 7: "COWH"}


def write_friction_tbl(cfg: Config) -> Path:
    """Write the FRICTION DATA FILE (.tbl) with one row per MATID zone."""
    zones = cfg.friction.zones
    lines = [
        "* Friction data file generated by hydromate",
        "* Bed roughness laws: NOFR | HAAL | CHEZ | STRI | MANN | NIKU | COWH",
        "* Columns: Fric_ID  BottomLaw  Coefficient  Mdef",
        "*",
    ]
    if not zones:
        # single default zone matching FRIC_ID = 1 from the geometry
        law = LAW_NAMES.get(cfg.friction.default_law, "MANN")
        lines.append(f"* zone 1: default")
        lines.append(f"1\t{law}\t{cfg.friction.default_coefficient:.4f}\tNULL")
    else:
        for z in sorted(zones, key=lambda z: z.matid):
            law = LAW_NAMES.get(z.law, "MANN")
            # data rows carry only numeric columns; names go in a '*' comment
            lines.append(f"* zone {z.matid}: {z.name}")
            lines.append(f"{z.matid}\t{law}\t{z.coefficient:.4f}\tNULL")
    lines.append("END")
    path = cfg.model_path(cfg.friction_tbl)
    path.write_text("\n".join(lines) + "\n")
    return path


def _prescribed_arrays(cfg: Config, liquids: list[LiquidBoundary],
                       inflow_q: float, outflow_wse: float) -> tuple[str, str, str]:
    """Build PRESCRIBED FLOWRATES / ELEVATIONS / VELOCITY PROFILES, ordered by
    liquid-boundary index. Unused slots get a harmless placeholder."""
    flow, elev, prof = [], [], []
    for lb in sorted(liquids, key=lambda b: b.index):
        if lb.kind == "inflow":
            flow.append(f"{inflow_q:.4f}")
            elev.append(f"{outflow_wse:.4f}")   # ignored for an inflow boundary
            prof.append("4")                    # ~ proportional to sqrt(depth)
        else:
            flow.append("0.")                   # ignored for an outflow boundary
            elev.append(f"{outflow_wse:.4f}")
            prof.append("1")                    # constant normal profile
    return ";".join(flow), ";".join(elev), ";".join(prof)


def write_cas(cfg: Config, liquids: list[LiquidBoundary],
              inflow_q: float, outflow_wse: float,
              gaia_cas: str | None = None) -> Path:
    """Write the TELEMAC-2D steering (.cas) file."""
    h = cfg.hydrodynamics
    flow, elev, prof = _prescribed_arrays(cfg, liquids, inflow_q, outflow_wse)
    n_liquid = len(liquids)

    lines: list[str] = [
        "/" + "-" * 68,
        f"/ TELEMAC2D steering file generated by hydromate for case '{cfg.name}'",
        f"/ regime: {h.regime}",
        "/" + "-" * 68,
        f"TITLE : '{cfg.name} {h.regime}'",
        "/",
        "/ INPUT / OUTPUT FILES",
        f"GEOMETRY FILE : {cfg.geometry_slf}",
        f"BOUNDARY CONDITIONS FILE : {cfg.boundary_cli}",
        f"RESULTS FILE : {cfg.results_slf}",
        "MASS-BALANCE : YES",
        "VARIABLES FOR GRAPHIC PRINTOUTS : 'U,V,S,B,H,Q,F'",
        "PRINTING CUMULATED FLOWRATES : YES",
        "/",
        "/ TIME",
        f"TIME STEP : {h.time_step}",
        f"NUMBER OF TIME STEPS : {h.n_time_steps}",
        f"GRAPHIC PRINTOUT PERIOD : {h.graphic_printout_period}",
        f"LISTING PRINTOUT PERIOD : {h.listing_printout_period}",
        "/",
        "/ NUMERICS",
        "ADVECTION : YES",
        "TREATMENT OF THE LINEAR SYSTEM : 2",
        "SCHEME FOR ADVECTION OF VELOCITIES : 14",
        "IMPLICITATION FOR DEPTH : 0.55",
        "IMPLICITATION FOR VELOCITY : 0.55",
        "MASS-LUMPING ON H : 1.",
        "MASS-LUMPING ON VELOCITY : 1.",
        "SOLVER : 1",
        "MAXIMUM NUMBER OF ITERATIONS FOR SOLVER : 200",
        "/",
        "/ TIDAL FLATS",
        "TIDAL FLATS : YES",
        "CONTINUITY CORRECTION : YES",
        "OPTION FOR THE TREATMENT OF TIDAL FLATS : 1",
        "TREATMENT OF NEGATIVE DEPTHS : 2",
        "/",
        "/ BOUNDARY CONDITIONS",
        f"PRESCRIBED FLOWRATES : {flow}",
        f"PRESCRIBED ELEVATIONS : {elev}",
        f"VELOCITY PROFILES : {prof}",
        f"OPTION FOR LIQUID BOUNDARIES : {';'.join(['1'] * n_liquid)}",
        "/",
        "/ FRICTION (zonal; coefficients calibrated by HydroBayesCal)",
        f"LAW OF BOTTOM FRICTION : {cfg.friction.default_law}",
        f"FRICTION COEFFICIENT : {cfg.friction.default_coefficient}",
        "FRICTION DATA : YES",
        f"FRICTION DATA FILE : {cfg.friction_tbl}",
        "LAW OF FRICTION ON LATERAL BOUNDARIES : 4",
        "ROUGHNESS COEFFICIENT OF BOUNDARIES : 0.03",
        "/",
        "/ INITIAL CONDITIONS",
        f"INITIAL CONDITIONS : '{h.initial_conditions}'",
        "/",
        "/ TURBULENCE",
        "DIFFUSION OF VELOCITY : YES",
        f"TURBULENCE MODEL : {h.turbulence_model}",
    ]

    if cfg.morphodynamics.enabled and gaia_cas:
        lines += ["/", "/ MORPHODYNAMICS (GAIA)", f"GAIA STEERING FILE : {gaia_cas}"]

    if h.extra_keywords:
        lines += ["/", "/ USER OVERRIDES"]
        for key, value in h.extra_keywords.items():
            lines.append(f"{key} : {value}")

    lines.append("&ETA")
    path = cfg.model_path(cfg.cas_file)
    path.write_text("\n".join(lines) + "\n")
    return path


def write_gaia_cas(cfg: Config) -> Path | None:
    """Write a minimal GAIA steering file (morphodynamic extension point).

    v1 emits a structurally valid GAIA .cas with the configured sediment classes
    and result file. Sediment-transport tuning is left to the user / calibration
    (e.g. CLASSES SHIELDS PARAMETERS perturbed by HydroBayesCal).
    """
    if not cfg.morphodynamics.enabled:
        return None
    m = cfg.morphodynamics
    classes = m.sediment_classes or [{"diameter": 0.001, "density": 2650}]
    diameters = ";".join(str(c.get("diameter", 0.001)) for c in classes)
    densities = ";".join(str(c.get("density", 2650)) for c in classes)
    shields = ";".join(str(c.get("shields", 0.047)) for c in classes)

    lines = [
        "/ GAIA steering file generated by hydromate",
        f"GAIA RESULTS FILE : {m.gaia_results_base}.slf",
        f"CLASSES SEDIMENT DIAMETERS : {diameters}",
        f"CLASSES SEDIMENT DENSITY : {densities}",
        f"CLASSES SHIELDS PARAMETERS : {shields}",
        "BED LOAD FOR ALL SANDS : YES",
        "BED-LOAD TRANSPORT FORMULA FOR ALL SANDS : 1",
    ]
    for key, value in m.extra_keywords.items():
        lines.append(f"{key} : {value}")
    lines.append("&ETA")
    path = cfg.model_path(cfg.gaia_cas)
    path.write_text("\n".join(lines) + "\n")
    return path
