"""Stage 4 - steering files: friction ``.tbl`` and the TELEMAC ``.cas`` (+ GAIA stub).

The friction table lists one row per MATID zone (``<id> <LAW> <coef> NULL``,
terminated by ``END``); node-to-zone linkage is carried by the ``FRIC_ID``
variable in the geometry SELAFIN (written in stage 2). HydroBayesCal perturbs the
coefficient column of this table during calibration.

The ``.cas`` is assembled from a small set of building blocks plus user overrides
so the case is reproducible and the prescribed boundary values stay consistent
with the liquid-boundary numbering from stage 3.
"""

from __future__ import annotations

import logging
from pathlib import Path

from hydromate.config import Config
from hydromate.boundary import LiquidBoundary

log = logging.getLogger("hydromate")

# friction-law number -> 4-letter name used in the .tbl
LAW_NAMES = {0: "NOFR", 1: "HAAL", 2: "CHEZ", 3: "STRI", 4: "MANN", 5: "NIKU", 7: "COWH"}


def _friction_rows(cfg: Config) -> list[tuple[int, int, float, str]]:
    """Return the friction zones as (fric_id, law, coefficient, name) rows.

    Priority: explicit ``friction.zones`` (MATID scheme) > the roughness zones
    (``inputs.roughness_zones`` + ``roughness_table``: one row per Zone ID with
    its ks under ``friction.roughness_law``, default NIKU) > a single default zone.
    """
    if cfg.friction.zones:
        return [(z.matid, z.law, z.coefficient, z.name)
                for z in sorted(cfg.friction.zones, key=lambda z: z.matid)]
    if cfg.inputs.roughness_zones is not None and cfg.inputs.roughness_table is not None:
        from hydromate.mesh import read_roughness_table

        table = read_roughness_table(cfg.inputs.roughness_table)
        return [(zid, cfg.friction.roughness_law, ks, f"roughness zone {zid}")
                for zid, ks in sorted(table.items())]
    return [(1, cfg.friction.default_law, cfg.friction.default_coefficient, "default")]


def _global_friction(cfg: Config) -> tuple[int, float]:
    """Effective (LAW OF BOTTOM FRICTION, FRICTION COEFFICIENT) for the .cas.

    With a FRICTION DATA FILE the per-zone laws/coefficients come from the .tbl;
    these globals just need to be consistent, so reuse the first .tbl row."""
    rows = _friction_rows(cfg)
    return rows[0][1], rows[0][2]


def write_friction_tbl(cfg: Config) -> Path:
    """Write the FRICTION DATA FILE (.tbl), one row per friction zone.

    Zones come from ``friction.zones`` (MATID) or, failing that, from the
    roughness zones (Zone ID -> ks via ``roughness_table``) so the rows match the
    geometry's per-node ``FRIC_ID``."""
    lines = [
        "* Friction data file generated by hydromate",
        "* Bed roughness laws: NOFR | HAAL | CHEZ | STRI | MANN | NIKU | COWH",
        "* Columns: Fric_ID  BottomLaw  Coefficient  Mdef",
        "*",
    ]
    for fric_id, law_num, coef, name in _friction_rows(cfg):
        law = LAW_NAMES.get(law_num, "MANN")
        # data rows carry only numeric columns; names go in a '*' comment
        lines.append(f"* zone {fric_id}: {name}")
        lines.append(f"{fric_id}\t{law}\t{coef:.4f}\tNULL")
    lines.append("END")
    path = cfg.model_path(cfg.friction_tbl)
    path.write_text("\n".join(lines) + "\n")
    return path


def _centerline_arclength(cfg: Config, mesh):
    """Per-node arc length: the along-reach distance of the nearest channel-
    centerline vertex, used to order channel nodes from upstream to downstream."""
    import geopandas as gpd
    import numpy as np
    from scipy.spatial import cKDTree
    from shapely.ops import linemerge, unary_union

    gdf = gpd.read_file(cfg.inputs.channel_centerline)
    if gdf.crs and gdf.crs.to_epsg() != cfg.crs_epsg:
        gdf = gdf.to_crs(epsg=cfg.crs_epsg)
    merged = unary_union(gdf.geometry.values)
    line = linemerge(merged) if merged.geom_type == "MultiLineString" else merged
    if line.geom_type == "MultiLineString":          # disjoint parts: take longest
        line = max(line.geoms, key=lambda g: g.length)
    n = max(2, int(line.length / 2.0))
    sline = np.linspace(0.0, line.length, n)
    cpts = np.array([[line.interpolate(d).x, line.interpolate(d).y] for d in sline])
    _, idx = cKDTree(cpts).query(np.column_stack([mesh.x, mesh.y]))
    return sline[idx]


def _longitudinal_prewet_depth(s_node, bottom, mask, depth_val, bed_percentile=25.0):
    """Pre-wet water depth from a *longitudinally smoothed thalweg* profile.

    Channel nodes are binned along the reach (arc length *s_node*); a low percentile
    of the bed per bin (the thalweg, robust to pits) is smoothed and interpolated
    into a target water surface ``wl(s) = thalweg(s) + depth_val``. The depth is
    ``max(wl - bottom, 0)`` on channel nodes (dry elsewhere): laterally near-flat per
    cross-section, following the reach gradient, ~``depth_val`` over the low-flow
    channel and tapering to 0 up the banks. Referencing the thalweg (not the section
    mean, which the high banks inflate) keeps the seeded surface close to the steady
    profile, so the hotstart drains only a little before converging - while still
    removing the jagged surface / channel-edge "dam" of a constant-depth seed that
    diverges on steep bathymetry.
    """
    import numpy as np

    s_ch, bed_ch = s_node[mask], bottom[mask]
    span = float(s_ch.max() - s_ch.min()) or 1.0
    nbins = int(np.clip(span / 5.0, 8, 400))             # ~5 m longitudinal bins
    edges = np.linspace(s_ch.min(), s_ch.max() + 1e-9, nbins + 1)
    which = np.clip(np.digitize(s_ch, edges) - 1, 0, nbins - 1)
    centers = 0.5 * (edges[:-1] + edges[1:])
    binbed = np.full(nbins, np.nan)
    for b in range(nbins):                               # per-bin thalweg (percentile)
        sel = bed_ch[which == b]
        if sel.size:
            binbed[b] = np.percentile(sel, bed_percentile)
    valid = ~np.isnan(binbed)
    binbed = np.interp(centers, centers[valid], binbed[valid])
    # moving-average smoothing along the reach (~1/25 of its length)
    k = max(1, nbins // 25)
    binbed = np.convolve(np.pad(binbed, k, mode="edge"),
                         np.ones(2 * k + 1) / (2 * k + 1), mode="valid")
    wl = np.interp(s_node, centers, binbed) + depth_val
    return np.where(mask, np.maximum(wl - bottom, 0.0), 0.0)


def write_initial_conditions(cfg: Config, mesh) -> Path:
    """Write the warm-start SELAFIN that pre-wets the channel for a stable cold start.

    Seeds WATER DEPTH on the ``*channel*`` mesh-zone nodes (zero velocity, dry
    elsewhere) on the geometry's own mesh; TELEMAC reads it as the PREVIOUS
    COMPUTATION FILE (see :func:`write_cas`) so the run continues from a pre-wetted
    channel instead of advancing the wetting front from a dry bed.

    With a channel centerline the seeded water surface is a *longitudinally smoothed*
    surface following the reach gradient (:func:`_longitudinal_prewet_depth`) - a
    constant depth instead makes the surface as jagged as the bed and leaves a depth
    "dam" at every channel/floodplain edge, which diverges at t=0 on steep terrain.
    Without a centerline it falls back to the simple constant-depth seed.
    """
    import numpy as np

    from hydromate import mesh as mesh_mod
    from hydromate import selafin

    depth_val = float(cfg.hydrodynamics.prewet_depth)
    mask = mesh_mod.channel_node_mask(cfg, mesh)
    if cfg.inputs.channel_centerline is not None:
        s_node = _centerline_arclength(cfg, mesh)
        depth = _longitudinal_prewet_depth(s_node, mesh.bottom, mask, depth_val)
        how = "smoothed longitudinal surface"
    else:
        depth = np.where(mask, depth_val, 0.0)
        how = "constant depth (no centerline)"
    path = cfg.model_path(cfg.ic_slf)
    selafin.write_initial_state(
        path, x=mesh.x, y=mesh.y, ikle=mesh.triangles + 1, ipobo=mesh.ipobo,
        depth=depth, title=f"{cfg.name} initial conditions",
    )
    log.info("  pre-wet %d/%d channel nodes (%s; ~%.2f m over thalweg, max %.2f m) -> %s",
             int(mask.sum()), mask.size, how, depth_val, float(depth.max()), path.name)
    return path


def _prescribed_arrays(cfg: Config, liquids: list[LiquidBoundary],
                       inflow_q: float, outflow_wse: float | None) -> tuple[str, str, str]:
    """Build PRESCRIBED FLOWRATES / ELEVATIONS / VELOCITY PROFILES, ordered by
    liquid-boundary index. Unused slots get a harmless placeholder.

    A free (Neumann) outflow prescribes nothing, so its elevation slot is a
    placeholder; ``stage_discharge`` / ``elevation`` instead prescribe *outflow_wse*.

    *inflow_q* is the **total** reach discharge. When several inflow boundaries
    exist (e.g. an upstream cross-section split by an island), it is distributed
    across them in proportion to their node count (a width/conveyance proxy) so the
    total prescribed inflow stays *inflow_q* - prescribing the full Q on each would
    multiply the supplied discharge and flood the domain.
    """
    free_outflow = cfg.hydrodynamics.outflow_condition == "free"
    inflows = [b for b in liquids if b.kind == "inflow"]
    inflow_nodes = sum(b.n_nodes for b in inflows) or 1
    flow, elev, prof = [], [], []
    for lb in sorted(liquids, key=lambda b: b.index):
        if lb.kind == "inflow":
            share = inflow_q * lb.n_nodes / inflow_nodes
            flow.append(f"{share:.4f}")
            elev.append("0.")                   # ignored for an inflow boundary
            prof.append("4")                    # ~ proportional to sqrt(depth)
        else:
            flow.append("0.")                   # ignored for an outflow boundary
            elev.append("0." if free_outflow else f"{outflow_wse:.4f}")
            prof.append("1")                    # constant normal profile
    return ";".join(flow), ";".join(elev), ";".join(prof)


def write_cas(cfg: Config, liquids: list[LiquidBoundary],
              inflow_q: float, outflow_wse: float | None = None,
              gaia_cas: str | None = None,
              previous_computation: str | None = None) -> Path:
    """Write the TELEMAC-2D steering (.cas) file.

    When *previous_computation* is given (the warm-start SELAFIN from
    :func:`write_initial_conditions`), the case is continued from it - the flow
    field (incl. the pre-wetted channel) is read from that file instead of the
    analytical INITIAL CONDITIONS, with the simulation clock reset to zero.
    """
    h = cfg.hydrodynamics
    flow, elev, prof = _prescribed_arrays(cfg, liquids, inflow_q, outflow_wse)
    n_liquid = len(liquids)

    if previous_computation:
        # since TELEMAC release 9.0 the boolean COMPUTATION CONTINUED keyword is
        # gone; supplying PREVIOUS COMPUTATION FILE alone triggers the continuation.
        initial_conditions = [
            "/ pre-wetted warm start (channel seeded with water; see hydromate)",
            f"PREVIOUS COMPUTATION FILE : {previous_computation}",
            "INITIAL TIME SET TO ZERO : YES",
        ]
    else:
        initial_conditions = [f"INITIAL CONDITIONS : '{h.initial_conditions}'"]

    lines: list[str] = [
        "/" + "-" * 68,
        f"/ TELEMAC2D steering file generated by hydromate for case '{cfg.name}'",
        f"/ regime: {h.regime}",
        "/" + "-" * 68,
        f"TITLE : '{cfg.name} {h.regime}'",
        "/",
        "/ INPUT / OUTPUT FILES",
        f"GEOMETRY FILE : {cfg.geometry_slf}",
        f"BOUNDARY CONDITIONS FILE : {cfg.boundary_cli}",
        f"RESULTS FILE : {cfg.results_slf}",
        "MASS-BALANCE : YES",
        # M = scalar velocity (sqrt(u^2+v^2)); written so the results carry
        # SCALAR VELOCITY directly, which HydroBayesCal reads as a calibration QoI.
        "VARIABLES FOR GRAPHIC PRINTOUTS : 'U,V,S,B,H,M,Q,F'",
        "PRINTING CUMULATED FLOWRATES : YES",
        "/",
        "/ TIME",
        f"TIME STEP : {h.time_step}",
        # CFL-adaptive marching: with VARIABLE TIME-STEP the TIME STEP above is just
        # the initial/maximum, and TELEMAC shrinks it to hold DESIRED COURANT NUMBER
        # (essential on the fine channel mesh, where a fixed 1 s step is unstable).
        *(["VARIABLE TIME-STEP : YES",
           f"DESIRED COURANT NUMBER : {h.desired_courant}"]
          if h.variable_timestep else []),
        f"NUMBER OF TIME STEPS : {h.n_time_steps}",
        f"GRAPHIC PRINTOUT PERIOD : {h.graphic_printout_period}",
        f"LISTING PRINTOUT PERIOD : {h.listing_printout_period}",
        "/",
    ]

    # numerics: finite volumes (default) vs finite elements -------------------
    turb_model = h.turbulence_model
    if h.finite_volumes:
        # FV accepts only constant viscosity (TELEMAC's init_fv.f rejects ITURB>=2:
        # 'TURBULENCE MODEL NOT TAKEN INTO ACCOUNT'); k-epsilon (3) /
        # Spalart-Allmaras (6) require the finite-element kernel.
        if turb_model != 1:
            log.warning("finite volumes accept only TURBULENCE MODEL 1 (constant "
                        "viscosity); overriding the configured model %d", turb_model)
            turb_model = 1
        lines += [
            "/ NUMERICS (finite volumes: robust for transcritical wetting/drying;",
            "/ explicit scheme -> time step is CFL-bound via VARIABLE TIME-STEP above)",
            "EQUATIONS : 'SAINT-VENANT FV'",
            f"FINITE VOLUME SCHEME : {h.finite_volume_scheme}",        # 5 = HLLC
            f"FINITE VOLUME SCHEME SPACE ORDER : {h.fv_space_order}",  # 2 = MUSCL
        ]
    else:
        lines += [
            "/ NUMERICS (finite elements)",
            "ADVECTION : YES",
            "TREATMENT OF THE LINEAR SYSTEM : 2",
            "SCHEME FOR ADVECTION OF VELOCITIES : 14",
            "IMPLICITATION FOR DEPTH : 0.55",
            "IMPLICITATION FOR VELOCITY : 0.55",
            "MASS-LUMPING ON H : 1.",
            "MASS-LUMPING ON VELOCITY : 1.",
            # a preconditioned solver (2 + PRECONDITIONING 2) converges where the
            # plain conjugate gradient (1) stalls on the ill-conditioned fine,
            # high-aspect channel-mesh system ('GRACJG EXCEEDING MAXIMUM ITERATIONS')
            f"SOLVER : {h.solver}",
            f"PRECONDITIONING : {h.preconditioning}",
            f"SOLVER ACCURACY : {h.solver_accuracy}",
            "MAXIMUM NUMBER OF ITERATIONS FOR SOLVER : 200",
        ]

    lines += [
        "/",
        "/ STABILITY CONTROLS",
        # damps free-surface instabilities over steep bed gradients (default 1.0)
        f"FREE SURFACE GRADIENT COMPATIBILITY : {h.free_surface_gradient_compat}",
        # clip H/U/V/T so a local spike can't cascade to NaN; a divergence guard
        "CONTROL OF LIMITS : YES",
        "LIMIT VALUES : -1000;9000;-1000;1000;-1000;1000;-1000;1000",
    ]
    # tidal flats: FE needs the explicit wetting/drying treatment; FV handles dry
    # fronts intrinsically (the HLLC Riemann solver), so this block is FE-only.
    if not h.finite_volumes:
        lines += [
            "/",
            "/ TIDAL FLATS",
            "TIDAL FLATS : YES",
            "CONTINUITY CORRECTION : YES",
            "OPTION FOR THE TREATMENT OF TIDAL FLATS : 1",
            "TREATMENT OF NEGATIVE DEPTHS : 2",
        ]

    lines += [
        "/",
        "/ BOUNDARY CONDITIONS",
        f"PRESCRIBED FLOWRATES : {flow}",
        f"PRESCRIBED ELEVATIONS : {elev}",
        f"VELOCITY PROFILES : {prof}",
        f"OPTION FOR LIQUID BOUNDARIES : {';'.join(['1'] * n_liquid)}",
        "/",
        "/ FRICTION (zonal; coefficients calibrated by HydroBayesCal)",
        f"LAW OF BOTTOM FRICTION : {_global_friction(cfg)[0]}",
        f"FRICTION COEFFICIENT : {_global_friction(cfg)[1]}",
        "FRICTION DATA : YES",
        f"FRICTION DATA FILE : {cfg.friction_tbl}",
        # lateral-boundary (wall) friction is a finite-element feature; the FV kernel
        # ignores it and then aborts ('WALL FRICTION NOT TAKEN INTO ACCOUNT'), so
        # emit it only for finite elements.
        *([f"LAW OF FRICTION ON LATERAL BOUNDARIES : {cfg.friction.boundary_law}",
           f"ROUGHNESS COEFFICIENT OF BOUNDARIES : {cfg.friction.boundary_coefficient}"]
          if not h.finite_volumes else []),
        "/",
        "/ INITIAL CONDITIONS",
        *initial_conditions,
        "/",
        "/ TURBULENCE",
        "DIFFUSION OF VELOCITY : YES",
        # constant eddy viscosity (model 1). With finite volumes this is the only
        # accepted model; VELOCITY DIFFUSIVITY sets the viscosity value.
        f"TURBULENCE MODEL : {turb_model}",
        *([f"VELOCITY DIFFUSIVITY : {h.velocity_diffusivity}"]
          if h.velocity_diffusivity is not None else []),
    ]

    if cfg.morphodynamics.enabled and gaia_cas:
        lines += ["/", "/ MORPHODYNAMICS (GAIA)", f"GAIA STEERING FILE : {gaia_cas}"]

    if h.extra_keywords:
        lines += ["/", "/ USER OVERRIDES"]
        for key, value in h.extra_keywords.items():
            lines.append(f"{key} : {value}")

    lines.append("&ETA")
    path = cfg.model_path(cfg.cas_file)
    path.write_text("\n".join(lines) + "\n")
    return path


def write_gaia_cas(cfg: Config) -> Path | None:
    """Write a minimal GAIA steering file (morphodynamic extension point).

    v1 emits a structurally valid GAIA .cas with the configured sediment classes
    and result file. Sediment-transport tuning is left to the user / calibration
    (e.g. CLASSES SHIELDS PARAMETERS perturbed by HydroBayesCal).
    """
    if not cfg.morphodynamics.enabled:
        return None
    m = cfg.morphodynamics
    classes = m.sediment_classes or [{"diameter": 0.001, "density": 2650}]
    diameters = ";".join(str(c.get("diameter", 0.001)) for c in classes)
    densities = ";".join(str(c.get("density", 2650)) for c in classes)
    shields = ";".join(str(c.get("shields", 0.047)) for c in classes)

    lines = [
        "/ GAIA steering file generated by hydromate",
        f"GAIA RESULTS FILE : {m.gaia_results_base}.slf",
        f"CLASSES SEDIMENT DIAMETERS : {diameters}",
        f"CLASSES SEDIMENT DENSITY : {densities}",
        f"CLASSES SHIELDS PARAMETERS : {shields}",
        "BED LOAD FOR ALL SANDS : YES",
        "BED-LOAD TRANSPORT FORMULA FOR ALL SANDS : 1",
    ]
    for key, value in m.extra_keywords.items():
        lines.append(f"{key} : {value}")
    lines.append("&ETA")
    path = cfg.model_path(cfg.gaia_cas)
    path.write_text("\n".join(lines) + "\n")
    return path
